name: Go CI/CD

on:
  push:
    branches: ["*"] # Runs on any branch
  pull_request:
    branches: ["*"] # Runs on PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Format check
        run: |
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build
        env:
          VERSION: "0.0.1"
          BUILD_INFO: ${{ github.ref }}-${{ github.ref_type }}-${{ github.sha }}
        run: |
          mkdir -p mybinaries
          go build -o mybinaries ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mybinaries
          path: mybinaries
